# Generated by Django 4.2.5 on 2023-09-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack', models.CharField(default='', max_length=50)),
                ('day', models.DateField(verbose_name='Friday')),
                ('time', models.DateTimeField(verbose_name='2023-09-08T10:08:40Z')),
                ('track', models.CharField(default='', max_length=50)),
                ('furl', models.CharField(max_length=200)),
                ('repo', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
