# Generated by Django 4.2.5 on 2023-09-08 22:55

from django.db import migrations, models
import endpointapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointapp', '0002_alter_track_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='date',
            field=models.DateField(default=endpointapp.models.get_date),
        ),
        migrations.AlterField(
            model_name='track',
            name='time',
            field=models.DateTimeField(verbose_name='2023-09-08T22:55:28Z'),
        ),
    ]
