# Generated by Django 4.2.5 on 2023-09-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointapp', '0003_track_date_alter_track_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='date',
        ),
        migrations.AlterField(
            model_name='track',
            name='time',
            field=models.DateTimeField(verbose_name='2023-09-08T22:57:28Z'),
        ),
    ]
